# Generated by Django 6.0.8 on 2026-08-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
