# Generated by Django 6.0.8 on 2026-08-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemaster',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='filemaster',
            name='original_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
