# Generated by Django 6.0.8 on 2026-08-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0002_filemaster_file_size_filemaster_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestoragelocation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
