# Generated by Django 6.0.8 on 2026-08-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_product_current_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
